-- 女優プロフィール情報カラムを actresses テーブルに追加
ALTER TABLE actresses
    ADD COLUMN bust SMALLINT UNSIGNED DEFAULT NULL AFTER debut_date,
    ADD COLUMN waist SMALLINT UNSIGNED DEFAULT NULL AFTER bust,
    ADD COLUMN hip SMALLINT UNSIGNED DEFAULT NULL AFTER waist,
    ADD COLUMN height SMALLINT UNSIGNED DEFAULT NULL AFTER hip,
    ADD COLUMN birthday DATE DEFAULT NULL AFTER height,
    ADD COLUMN blood_type VARCHAR(10) DEFAULT NULL AFTER birthday,
    ADD COLUMN hobby VARCHAR(500) DEFAULT NULL AFTER blood_type,
    ADD COLUMN prefectures VARCHAR(100) DEFAULT NULL AFTER hobby,
    ADD COLUMN comment TEXT DEFAULT NULL AFTER prefectures;
